#coding: utf-8
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NgWordsController do

  before :all do
    FactoryGirl.create(:account)
    @logged_in_account = Account.last
  end

  # This should return the minimal set of attributes required to create a valid
  # NgWord. As you add validations to NgWord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "account_id" => @logged_in_account.id, "word"=>"hogehoge" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NgWordsController. Be sure to keep this updated too.
  let(:valid_session) { {:account_id => @logged_in_account.id} }

  describe "GET new" do
    it "assigns a new ng_word as @ng_word" do
      get :new, {}, valid_session
      expect(assigns(:ng_word)).to be_a_new(NgWord)
    end
  end

  describe "GET edit" do
    it "assigns the requested ng_word as @ng_word" do
      ng_word = NgWord.create! valid_attributes
      get :edit, {:id => ng_word.to_param}, valid_session
      expect(assigns(:ng_word)).to eq(ng_word)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NgWord" do
        expect {
          post :create, {:ng_word => valid_attributes}, valid_session
        }.to change(NgWord, :count).by(1)
      end

      it "assigns a newly created ng_word as @ng_word" do
        post :create, {:ng_word => valid_attributes}, valid_session
        assigns(:ng_word).should be_a(NgWord)
        assigns(:ng_word).should be_persisted
      end

      it "redirects to the logged in account " do
        post :create, {:ng_word => valid_attributes}, valid_session
        response.should redirect_to(@logged_in_account)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ng_word as @ng_word" do
        # Trigger the behavior that occurs when invalid params are submitted
        NgWord.any_instance.stub(:save).and_return(false)
        post :create, {:ng_word => { :word => "" }}, valid_session
        assigns(:ng_word).should be_a_new(NgWord)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NgWord.any_instance.stub(:save).and_return(false)
        post :create, {:ng_word => { :word => "" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "when succeeds, " do
      it "updates the requested ng_word" do
        ng_word = NgWord.create! valid_attributes
        # Assuming there are no other ng_words in the database, this
        # specifies that the NgWord created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NgWord.any_instance.should_receive(:update_attributes).with({ "word" => "changed" })
        put :update, {:id => ng_word.to_param, :ng_word => { "word" => "changed" }}, valid_session
      end

      it "assigns the requested ng_word as @ng_word" do
        ng_word = NgWord.create! valid_attributes
        put :update, {:id => ng_word.to_param, :ng_word => valid_attributes}, valid_session
        assigns(:ng_word).should eq(ng_word)
      end

      it "redirects to the logged in account" do
        ng_word = NgWord.create! valid_attributes
        put :update, {:id => ng_word.to_param, :ng_word => valid_attributes}, valid_session
        response.should redirect_to(@logged_in_account)
      end
    end

    describe "when fails, " do
      it "assigns the ng_word as @ng_word" do
        ng_word = NgWord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NgWord.any_instance.stub(:save).and_return(false)
        put :update, {:id => ng_word.to_param, :ng_word => valid_attributes }, valid_session
        assigns(:ng_word).should eq(ng_word)
      end

      it "re-renders the 'edit' template" do
        ng_word = NgWord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NgWord.any_instance.stub(:save).and_return(false)
        put :update, {:id => ng_word.to_param, :ng_word => valid_attributes}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ng_word" do
      ng_word = NgWord.create! valid_attributes
      expect {
        delete :destroy, {:id => ng_word.to_param}, valid_session
      }.to change(NgWord, :count).by(-1)
    end

    it "redirects to the ng_words list" do
      ng_word = NgWord.create! valid_attributes
      delete :destroy, {:id => ng_word.to_param}, valid_session
      response.should redirect_to(@logged_in_account)
    end
  end

end
